// Code generated by mockery v2.45.0. DO NOT EDIT.

//go:build !compile

package bridge

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// MockConnector is an autogenerated mock type for the Connector type
type MockConnector struct {
	mock.Mock
}

type MockConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnector) EXPECT() *MockConnector_Expecter {
	return &MockConnector_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: ctx, id
func (_m *MockConnector) Connect(ctx context.Context, id uint64) (net.Conn, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (net.Conn, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) net.Conn); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnector_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockConnector_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockConnector_Expecter) Connect(ctx interface{}, id interface{}) *MockConnector_Connect_Call {
	return &MockConnector_Connect_Call{Call: _e.mock.On("Connect", ctx, id)}
}

func (_c *MockConnector_Connect_Call) Run(run func(ctx context.Context, id uint64)) *MockConnector_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockConnector_Connect_Call) Return(_a0 net.Conn, _a1 error) *MockConnector_Connect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnector_Connect_Call) RunAndReturn(run func(context.Context, uint64) (net.Conn, error)) *MockConnector_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnector creates a new instance of MockConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnector {
	mock := &MockConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
