// Code generated by mockery v2.45.0. DO NOT EDIT.

//go:build !compile

package bridge

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// MockContextDialer is an autogenerated mock type for the ContextDialer type
type MockContextDialer struct {
	mock.Mock
}

type MockContextDialer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContextDialer) EXPECT() *MockContextDialer_Expecter {
	return &MockContextDialer_Expecter{mock: &_m.Mock}
}

// DialContext provides a mock function with given fields: ctx, network, address
func (_m *MockContextDialer) DialContext(ctx context.Context, network string, address string) (net.Conn, error) {
	ret := _m.Called(ctx, network, address)

	if len(ret) == 0 {
		panic("no return value specified for DialContext")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (net.Conn, error)); ok {
		return rf(ctx, network, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) net.Conn); ok {
		r0 = rf(ctx, network, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, network, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContextDialer_DialContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialContext'
type MockContextDialer_DialContext_Call struct {
	*mock.Call
}

// DialContext is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - address string
func (_e *MockContextDialer_Expecter) DialContext(ctx interface{}, network interface{}, address interface{}) *MockContextDialer_DialContext_Call {
	return &MockContextDialer_DialContext_Call{Call: _e.mock.On("DialContext", ctx, network, address)}
}

func (_c *MockContextDialer_DialContext_Call) Run(run func(ctx context.Context, network string, address string)) *MockContextDialer_DialContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockContextDialer_DialContext_Call) Return(_a0 net.Conn, _a1 error) *MockContextDialer_DialContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContextDialer_DialContext_Call) RunAndReturn(run func(context.Context, string, string) (net.Conn, error)) *MockContextDialer_DialContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContextDialer creates a new instance of MockContextDialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContextDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContextDialer {
	mock := &MockContextDialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
